# Ruff Configuration

# Python version to target
target-version = "py313"
# Line length settings for both lint and format
line-length = 100

# Exclude some directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
]

[lint]
# Enable all rules by default
select = ["E", "F", "B", "I", "N", "UP", "ANN", "S", "A", "C4", "Q", "RUF", "D"]

# Ignore specific rules that might be too noisy initially
ignore = [
    "D203",    # 1 blank line required before class docstring
    "D212",    # Multi-line docstring summary should start at the first line
]

[format]
# Sort imports
docstring-code-format = true
docstring-code-line-length = 80 